import { Injectable } from '@angular/core';

export const CITY_STATES: Record<string, string> = {
  "Mumbai": "Maharashtra",
  "Delhi": "Delhi",
  "Bangalore": "Karnataka",
  "Hyderabad": "Andhra Pradesh",
  "Ahmedabad": "Gujarat",
  "Chennai": "Tamil Nadu",
  "Kolkata": "West Bengal",
  "Surat": "Gujarat",
  "Pune": "Maharashtra",
  "Jaipur": "Rajasthan",
  "Lucknow": "Uttar Pradesh",
  "Kanpur": "Uttar Pradesh",
  "Nagpur": "Maharashtra",
  "Indore": "Madhya Pradesh",
  "Thane": "Maharashtra",
  "Bhopal": "Madhya Pradesh",
  "Visakhapatnam": "Andhra Pradesh",
  "Pimpri and Chinchwad": "Maharashtra",
  "Patna": "Bihar",
  "Vadodara": "Gujarat",
  "Ghaziabad": "Uttar Pradesh",
  "Ludhiana": "Punjab",
  "Agra": "Uttar Pradesh",
  "Nashik": "Maharashtra",
  "Faridabad": "Haryana",
  "Meerut": "Uttar Pradesh",
  "Rajkot": "Gujarat",
  "Kalyan and Dombivali": "Maharashtra",
  "Vasai Virar": "Maharashtra",
  "Varanasi": "Uttar Pradesh",
  "Srinagar": "Jammu and Kashmir",
  "Aurangabad": "Maharashtra",
  "Dhanbad": "Jharkhand",
  "Amritsar": "Punjab",
  "Navi Mumbai": "Maharashtra",
  "Allahabad": "Uttar Pradesh",
  "Haora": "West Bengal",
  "Ranchi": "Jharkhand",
  "Gwalior": "Madhya Pradesh",
  "Jabalpur": "Madhya Pradesh",
  "Coimbatore": "Tamil Nadu",
  "Vijayawada": "Andhra Pradesh",
  "Jodhpur": "Rajasthan",
  "Madurai": "Tamil Nadu",
  "Raipur": "Chhattisgarh",
  "Kota": "Rajasthan",
  "Chandigarh": "Chandigarh",
  "Guwahati": "Assam",
  "Solapur": "Maharashtra",
  "Hubli and Dharwad ": "Karnataka",
  "Bareilly": "Uttar Pradesh",
  "Mysore": "Karnataka",
  "Moradabad": "Uttar Pradesh",
  "Gurgaon": "Haryana",
  "Aligarh": "Uttar Pradesh",
  "Jalandhar": "Punjab",
  "Tiruchirappalli": "Tamil Nadu",
  "Bhubaneswar": "Orissa",
  "Salem": "Tamil Nadu",
  "Mira and Bhayander": "Maharashtra",
  "Thiruvananthapuram": "Kerala",
  "Bhiwandi": "Maharashtra",
  "Saharanpur": "Uttar Pradesh",
  "Gorakhpur": "Uttar Pradesh",
  "Guntur": "Andhra Pradesh",
  "Amravati": "Maharashtra",
  "Bikaner": "Rajasthan",
  "Noida": "Uttar Pradesh",
  "Jamshedpur": "Jharkhand",
  "Bhilai Nagar": "Chhattisgarh",
  "Warangal": "Andhra Pradesh",
  "Cuttack": "Orissa",
  "Firozabad": "Uttar Pradesh",
  "Kochi": "Kerala",
  "Bhavnagar": "Gujarat",
  "Dehradun": "Uttarakhand",
  "Durgapur": "West Bengal",
  "Asansol": "West Bengal",
  "Nanded Waghala": "Maharashtra",
  "Kolapur": "Maharashtra",
  "Ajmer": "Rajasthan",
  "Gulbarga": "Karnataka",
  "Loni": "Uttar Pradesh",
  "Ujjain": "Madhya Pradesh",
  "Siliguri": "West Bengal",
  "Ulhasnagar": "Maharashtra",
  "Jhansi": "Uttar Pradesh",
  "Sangli Miraj Kupwad": "Maharashtra",
  "Jammu": "Jammu and Kashmir",
  "Nellore": "Andhra Pradesh",
  "Mangalore": "Karnataka",
  "Belgaum": "Karnataka",
  "Jamnagar": "Gujarat",
  "Tirunelveli": "Tamil Nadu",
  "Malegaon": "Maharashtra",
  "Gaya": "Bihar",
  "Ambattur": "Tamil Nadu",
  "Jalgaon": "Maharashtra",
  "Udaipur": "Rajasthan",
  "Maheshtala": "West Bengal",
  "Tiruppur": "Tamil Nadu",
  "Davanagere": "Karnataka",
  "Kozhikode": "Kerala",
  "Kurnool": "Andhra Pradesh",
  "Akola": "Maharashtra",
  "Rajpur Sonarpur": "West Bengal",
  "Bokaro Steel": "Jharkhand",
  "Bellary": "Karnataka",
  "Patiala": "Punjab",
  "South Dum Dum": "West Bengal",
  "Rajarhat Gopalpur": "West Bengal",
  "Bhagalpur": "Bihar",
  "Agartala": "Tripura",
  "Muzaffarnagar": "Uttar Pradesh",
  "Bhatpara": "West Bengal",
  "Latur": "Maharashtra",
  "Panihati": "West Bengal",
  "Dhule": "Maharashtra",
  "Rohtak": "Haryana",
  "Korba": "Chhattisgarh",
  "Bhilwara": "Rajasthan",
  "Brahmapur Town": "Orissa",
  "Muzaffarpur": "Bihar",
  "Ahmadnagar": "Maharashtra",
  "Mathura": "Uttar Pradesh",
  "Kollam": "Kerala",
  "Avadi": "Tamil Nadu",
  "Kadapa": "Andhra Pradesh",
  "Rajahmundry": "Andhra Pradesh",
  "Bilaspur": "Chhattisgarh",
  "Kamarhati": "West Bengal",
  "Shahjahanpur": "Uttar Pradesh",
  "Bijapur": "Karnataka",
  "Rampur": "Uttar Pradesh",
  "Shimoga": "Karnataka",
  "Chandrapur": "Maharashtra",
  "Junagadh": "Gujarat",
  "Thrissur": "Kerala",
  "Alwar": "Rajasthan",
  "Barddhaman": "West Bengal",
  "Kulti": "West Bengal",
  "Kakinada": "Andhra Pradesh",
  "Nizamabad": "Andhra Pradesh",
  "Parbhani": "Maharashtra",
  "Tumkur": "Karnataka",
  "Hisar": "Haryana",
  "Ozhukarai": "Puducherry",
  "Biharsharif": "Bihar",
  "Darbhanga": "Bihar",
  "Panipat": "Haryana",
  "Aizawl": "Mizoram",
  "Bally": "West Bengal",
  "Dewas": "Madhya Pradesh",
  "Tirupati": "Andhra Pradesh",
  "Ichalkaranji": "Maharashtra",
  "Karnal": "Haryana",
  "Bathinda": "Punjab",
  "Jalna": "Maharashtra",
  "Kirari Suleman Nagar": "Delhi",
  "Purnia": "Bihar",
  "Satna": "Madhya Pradesh",
  "Maunath Bhanjan": "Uttar Pradesh",
  "Barasat": "West Bengal",
  "Sonipat": "Haryana",
  "Farrukhabad and Fatehgarh": "Uttar Pradesh",
  "Sagar": "Madhya Pradesh",
  "Raurkela": "Orissa",
  "Durg": "Chhattisgarh",
  "Imphal": "Manipur",
  "Ratlam": "Madhya Pradesh",
  "Hapur": "Uttar Pradesh",
  "Arrah": "Bihar",
  "Karimnagar": "Andhra Pradesh",
  "Anantapur": "Andhra Pradesh",
  "NDMC": "Delhi",
  "Etawah": "Uttar Pradesh",
  "Ambernath": "Maharashtra",
  "Bharatpur": "Rajasthan",
  "Begusarai": "Bihar",
  "Tiruvottiyur": "Tamil Nadu",
  "North Dum Dum": "West Bengal",
  "Gandhidham": "Gujarat",
  "Baranagar": "West Bengal",
  "Puducherry": "Puducherry",
  "Thoothukkudi": "Tamil Nadu",
  "Sikar": "Rajasthan",
  "Rewa": "Madhya Pradesh",
  "Mirzapur and Vindhyachal": "Uttar Pradesh",
  "Raichur": "Karnataka",
  "Pali": "Rajasthan",
  "Ramagundam": "Andhra Pradesh",
  "Hardwar": "Uttarakhand",
  "Vizianagaram": "Andhra Pradesh",
  "Katihar": "Bihar",
  "Nagercoil": "Tamil Nadu",
  "Ganganagar": "Rajasthan",
  "Karawal Nagar": "Delhi",
  "Mango": "Jharkhand",
  "Thanjavur": "Tamil Nadu",
  "Bulandshahr": "Uttar Pradesh",
  "Uluberia": "West Bengal",
  "Murwara": "Madhya Pradesh",
  "Sambhal": "Uttar Pradesh",
  "Singrauli": "Madhya Pradesh",
  "Nadiad": "Gujarat",
  "Secunderabad": "Andhra Pradesh",
  "Naihati": "West Bengal",
  "Yamunanagar": "Haryana",
  "Bidhan Nagar": "West Bengal",
  "Pallavaram": "Tamil Nadu",
  "Bidar": "Karnataka",
  "Munger": "Bihar",
  "Panchkula": "Haryana",
  "Burhanpur": "Madhya Pradesh",
  "Raurkela Industrial Township": "Orissa",
  "Kharagpur": "West Bengal",
  "Dindigul": "Tamil Nadu",
  "Hospet": "Karnataka",
  "Gandhinagar": "Gujarat",
  "Nangloi Jat": "Delhi",
  "English Bazar": "West Bengal",
  "Ongole": "Andhra Pradesh",
  "Eluru": "Andhra Pradesh",
  "Deoghar": "Jharkhand",
  "Chapra": "Bihar",
  "Haldia": "West Bengal",
  "Khandwa": "Madhya Pradesh",
  "Puri Town": "Orissa",
  "Nandyal": "Andhra Pradesh",
  "Morena": "Madhya Pradesh",
  "Amroha": "Uttar Pradesh",
  "Anand": "Gujarat",
  "Bhind": "Madhya Pradesh",
  "Bhalswa Jahangir Pur": "Delhi",
  "Madhyamgram": "West Bengal",
  "Bhiwani": "Haryana",
  "Navi Mumbai Panvel Raigad": "Maharashtra",
  "Baharampur": "West Bengal",
  "Ambala": "Haryana",
  "Morvi": "Gujarat",
  "Fatehpur": "Uttar Pradesh",
  "Rae Bareli": "Uttar Pradesh",
  "Khora": "Uttar Pradesh",
  "Bhusawal": "Maharashtra",
  "Orai": "Uttar Pradesh",
  "Bahraich": "Uttar Pradesh",
  "Vellore": "Tamil Nadu",
  "Mahesana": "Gujarat",
  "Khammam": "Andhra Pradesh",
  "Sambalpur": "Orissa",
  "Raiganj": "West Bengal",
  "Sirsa": "Haryana",
  "Dinapur Nizamat": "Bihar",
  "Serampore": "West Bengal",
  "Sultan Pur Majra": "Delhi",
  "Guna": "Madhya Pradesh",
  "Jaunpur": "Uttar Pradesh",
  "Panvel": "Maharashtra",
  "Shivpuri": "Madhya Pradesh",
  "Surendranagar Dudhrej": "Gujarat",
  "Unnao": "Uttar Pradesh",
  "Hugli and Chinsurah": "West Bengal",
  "Sitapur": "Uttar Pradesh",
  "Hastsal": "Delhi",
  "Tambaram": "Tamil Nadu",
  "Adityapur": "Jharkhand",
  "Badalapur": "Maharashtra",
  "Alappuzha": "Kerala",
  "Cuddalore": "Tamil Nadu",
  "Silchar": "Assam",
  "Gadag and Betigeri": "Karnataka",
  "Bahadurgarh": "Haryana",
  "Machilipatnam": "Andhra Pradesh",
  "Shimla": "Himachal Pradesh",
  "Medinipur": "West Bengal",
  "Deoli": "Delhi",
  "Bharuch": "Gujarat",
  "Hoshiarpur": "Punjab",
  "Jind": "Haryana",
  "Chandannagar": "West Bengal",
  "Adoni": "Andhra Pradesh",
  "Tonk": "Rajasthan",
  "Faizabad": "Uttar Pradesh",
  "Tenali": "Andhra Pradesh",
  "Alandur": "Tamil Nadu",
  "Kancheepuram": "Tamil Nadu",
  "Vapi": "Gujarat",
  "Rajnandgaon": "Chhattisgarh",
  "Proddatur": "Andhra Pradesh",
  "Navsari": "Gujarat",
  "Budaun": "Uttar Pradesh",
  "Uttarpara Kotrung": "West Bengal",
  "Mahbubnagar": "Andhra Pradesh",
  "Erode": "Tamil Nadu",
  "Batala": "Punjab",
  "Saharsa": "Bihar",
  "Haldwani and Kathgodam": "Uttarakhand",
  "Vidisha": "Madhya Pradesh",
  "Thanesar": "Haryana",
  "Kishangarh": "Rajasthan",
  "Dallo Pura": "Delhi",
  "Veraval": "Gujarat",
  "Banda": "Uttar Pradesh",
  "Chittoor": "Andhra Pradesh",
  "Krishnanagar": "West Bengal",
  "Barrackpur": "West Bengal",
  "Lakhimpur": "Uttar Pradesh",
  "Santipur": "West Bengal",
  "Porbandar": "Gujarat",
  "Hindupur": "Andhra Pradesh",
  "Balurghat": "West Bengal",
  "Bhadravati": "Karnataka",
  "Hanumangarh": "Rajasthan",
  "Moga": "Punjab",
  "Pathankot": "Punjab",
  "Hajipur": "Bihar",
  "Sasaram": "Bihar",
  "Habra": "West Bengal",
  "Bid": "Maharashtra",
  "Mohali": "Punjab",
  "Burari": "Delhi",
  "Beawar": "Rajasthan",
  "Abohar": "Punjab",
  "Tiruvannamalai": "Tamil Nadu",
  "Jamuria": "West Bengal",
  "Kaithal": "Haryana",
  "Godhra": "Gujarat",
  "Bhuj": "Gujarat",
  "Robertson Pet": "Karnataka",
  "Shillong": "Meghalaya",
  "Rewari": "Haryana",
  "Hazaribag": "Jharkhand",
  "Bhimavaram": "Andhra Pradesh",
  "Mandsaur": "Madhya Pradesh",
  "Chas": "Jharkhand",
  "Rudrapur": "Uttarakhand",
  "Chitradurga": "Karnataka",
  "Kumbakonam": "Tamil Nadu",
  "Dibrugarh": "Assam",
  "Kolar": "Karnataka",
  "Chhindwara": "Madhya Pradesh",
  "Bankura": "West Bengal",
  "Mandya": "Karnataka",
  "Dehri": "Bihar",
  "Raigarh": "Chhattisgarh",
  "Madanapalle": "Andhra Pradesh",
  "Nalgonda": "Andhra Pradesh",
  "Hathras": "Uttar Pradesh",
  "Malerkotla": "Punjab",
  "Siwan": "Bihar",
  "Chhattarpur": "Madhya Pradesh",
  "Hassan": "Karnataka",
  "Lalitpur": "Uttar Pradesh",
  "Gondiya": "Maharashtra",
  "North Barrackpur": "West Bengal",
  "Bettiah": "Bihar",
  "Palakkad": "Kerala",
  "Rajapalayam": "Tamil Nadu",
  "Botad": "Gujarat",
  "Modinagar": "Uttar Pradesh",
  "Deoria": "Uttar Pradesh",
  "Raniganj": "West Bengal",
  "Palwal": "Haryana",
  "Khanna": "Punjab",
  "Neemuch": "Madhya Pradesh",
  "Pilibhit": "Uttar Pradesh",
  "Mustafabad": "Delhi",
  "Hardoi": "Uttar Pradesh",
  "Guntakal": "Andhra Pradesh",
  "Pithampur": "Madhya Pradesh",
  "Motihari": "Bihar",
  "Dhaulpur": "Rajasthan",
  "Srikakulam": "Andhra Pradesh",
  "Nabadwip": "West Bengal",
  "Patan": "Gujarat",
  "Jagdalpur": "Chhattisgarh",
  "Udupi": "Karnataka",
  "Basirhat": "West Bengal",
  "Damoh": "Madhya Pradesh",
  "Halisahar": "West Bengal",
  "Jagadhri": "Haryana",
  "Rishra": "West Bengal",
  "Kurichi": "Tamil Nadu",
  "Dimapur": "Nagaland",
  "Palanpur": "Gujarat",
  "Dharmavaram": "Andhra Pradesh",
  "Gokal Pur": "Delhi",
  "Kashipur": "Uttarakhand",
  "Ashokenagar Kalyangarh": "West Bengal",
  "Baidyabati": "West Bengal",
  "Sawai Madhopur": "Rajasthan",
  "Puruliya": "West Bengal",
  "Mandoli": "Delhi",
  "Mainpuri": "Uttar Pradesh",
  "Kanchrapara": "West Bengal",
  "Satara": "Maharashtra",
  "Churu": "Rajasthan",
  "Madavaram": "Tamil Nadu",
  "Gangapur": "Rajasthan",
  "Dabgram": "West Bengal",
  "Darjiling": "West Bengal",
  "Barshi": "Maharashtra",
  "Etah": "Uttar Pradesh",
  "Jhunjhunun": "Rajasthan",
  "Chikmagalur": "Karnataka",
  "Jetpur Navagadh": "Gujarat",
  "Roorkee": "Uttarakhand",
  "Gudivada": "Andhra Pradesh",
  "Baleshwar": "Orissa",
  "Baran": "Rajasthan",
  "Hoshangabad": "Madhya Pradesh",
  "Nagaon": "Assam",
  "Pudukkottai": "Tamil Nadu",
  "Adilabad": "Andhra Pradesh",
  "Hosur": "Tamil Nadu",
  "Muktsar": "Punjab",
  "Yavatmal": "Maharashtra",
  "Titagarh": "West Bengal",
  "Barnala": "Punjab",
  "Chittaurgarh": "Rajasthan",
  "Narasaraopet": "Andhra Pradesh",
  "Dum Dum": "West Bengal",
  "Basti": "Uttar Pradesh",
  "Valsad": "Gujarat",
  "Ambur": "Tamil Nadu",
  "Giridih": "Jharkhand",
  "Chandausi": "Uttar Pradesh",
  "Gonda": "Uttar Pradesh",
  "Bally Town": "West Bengal",
  "Kalol": "Gujarat",
  "Bagaha": "Bihar",
  "Ambikapur": "Chhattisgarh",
  "Achalpur": "Maharashtra",
  "Gondal": "Gujarat",
  "Bagalkot": "Karnataka",
  "Osmanabad": "Maharashtra",
  "Akbarpur": "Uttar Pradesh",
  "Champdani": "West Bengal",
  "Deesa": "Gujarat",
  "Khurja": "Uttar Pradesh",
  "Nandurbar": "Maharashtra",
  "Azamgarh": "Uttar Pradesh",
  "Ghazipur": "Uttar Pradesh",
  "Delhi Cantonment": "Delhi",
  "Firozpur": "Punjab",
  "Baripada": "Orissa",
  "Mughalsarai": "Uttar Pradesh",
  "Anantnag": "Jammu and Kashmir",
  "Sehore": "Madhya Pradesh",
  "Bongaon": "West Bengal",
  "Kanpur Cantonment": "Uttar Pradesh",
  "Khardaha": "West Bengal",
  "Tadpatri": "Andhra Pradesh",
  "Port Blair": "Andaman and Nicobar Islands",
  "Sultanpur": "Uttar Pradesh",
  "Bhadrak": "Orissa",
  "Shikohabad": "Uttar Pradesh",
  "Jalpaiguri": "West Bengal",
  "Shamli": "Uttar Pradesh",
  "Karaikkudi": "Tamil Nadu",
  "Khargone": "Madhya Pradesh",
  "Wardha": "Maharashtra",
  "Ranibennur": "Karnataka",
  "Kishanganj": "Bihar",
  "Neyveli": "Tamil Nadu",
  "Amreli": "Gujarat",
  "Suryapet": "Andhra Pradesh",
  "Gangawati": "Karnataka",
  "Hindaun": "Rajasthan",
  "Jamalpur": "Bihar",
  "Bhiwadi": "Rajasthan",
  "Ballia": "Uttar Pradesh",
  "Bansberia": "West Bengal",
  "Tadepalligudem": "Andhra Pradesh",
  "Miryalaguda": "Andhra Pradesh",
  "Baraut": "Uttar Pradesh",
  "Udgir": "Maharashtra",
  "Betul": "Madhya Pradesh",
  "Bundi": "Rajasthan",
  "Jehanabad": "Bihar",
  "Ambala Sadar": "Haryana",
  "Nagapattinam": "Tamil Nadu",
  "Nagaur": "Rajasthan",
  "Buxar": "Bihar",
  "Seoni": "Madhya Pradesh",
  "aurangabad": "Bihar",
  "Greater Noida": "Uttar Pradesh",
  "Hinganghat": "Maharashtra",
  "Sujangarh": "Rajasthan",
  "Bhadreswar": "West Bengal",
  "Chilakaluripet": "Andhra Pradesh",
  "Kasganj": "Uttar Pradesh",
  "Kalyani": "West Bengal",
  "Gangtok": "Sikkim",
  "Datia": "Madhya Pradesh",
  "Nagda": "Madhya Pradesh",
  "Banswara": "Rajasthan",
  "Kapurthala": "Punjab"
};

@Injectable({
  providedIn: 'root'
})
export class UtilityService {


  constructor() { }
}
